### PR TITLE
Add support for swagger groups

### PR DESCRIPTION
**Pull request by vlaurin**
Script `bin/publish-swagger-docs.sh` only works with Swagger `default` group. For projects that split their API documentation in multiple groups (e.g. v1/v2), the script can't be used as the `default` group doesn't exist.

This PR adds a second script `bin/publish-swagger-group-docs.sh` which follows the steps of `publish-swagger-docs.sh` but accepts one or multiple groups as arguments and publish the documentation for those one by one.

An example of use can be found in build: [ccd-data-store-api#2032](https://travis-ci.org/hmcts/ccd-data-store-api/builds/446921562), which published both: 
* [ccd-data-store-api.v1.json](https://github.com/hmcts/reform-api-docs/blob/master/docs/specs/ccd-data-store-api.v1.json)
* [ccd-data-store-api.v2.json](https://github.com/hmcts/reform-api-docs/blob/master/docs/specs/ccd-data-store-api.v2.json)

### CODE REVIEW

**Comment by rkondratowicz** [comment]
API should **NOT** be versioned using URL
https://hmcts.github.io/restful-api-standards/#115

**Comment by vlaurin** [comment]
@doncem @rkondratowicz We're not versioning by URL, but by media type as defined by programme standards.

The need for grouping is very much independent of the versioning strategy; the aim is to provide developers a documentation that is relevant to them and easy to consume.

Looking at the [investigation](https://tools.hmcts.net/jira/browse/RPE-502?focusedCommentId=453212&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-453212), it does emphasise a need for grouping independent of versioning.

We are using an approach very similar to what's described by the spike, where we've got multiple dockets in our Swagger configuration.
However, the spike stops at the Swagger configuration for multiple groups, but doesn't consider the fact that this approach is not compatible with the current `publish-swagger-docs.sh` script.

This is what this PR is about, and it seems aligned with the spike which was conducted.

Grouping multiple APIs into a single Docket like done in rpe-feature-toggle defeats the purpose which is to have completely distinct documentation page.

**Comment by vlaurin** [comment]
Thanks, examples have been updated to `group1` and `group2`.

**Comment by doncem** [comment]
@vlaurin do you want to look at #54 ? Gets rid of the need of docker setup and `.env` requirement. Just grabs everything with integration testing.

**Comment by vlaurin** [comment]
Yes, I saw that, that's why I'm keeping the PR open. I do agree with the approach promoted by #54, so I'm keen to add support for groups to this one as well. However, this will be in addition to the initial Docker one which we still need while we try and transition to the new approach.

**Pull request merged**
